Importing numpy, as np is convention for abbreviate numpy library in python

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int64')

In [5]:
a.ndim
# ndim is used for getting number of axes of an array

1

In [6]:
a.size
# size is used to know the array length

3

In [7]:
a.shape

(3,)

In [8]:
b = np.array([[1.3, 2.4], [0.3, 4.1]])

In [9]:
b.dtype

dtype('float64')

In [10]:
b.ndim

2

In [11]:
b.size

4

In [12]:
b.shape

(2, 2)

In [13]:
# We can use tuple to create an array instead using list or using both of them
c = np.array(((1,2,3), (4,5,6)))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
d = np.array([(1,2,3), [4,5,6], (7,8,9)])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
e = np.array([['a', 'b'], ['c', 'd']])
e

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [16]:
e.dtype

dtype('<U1')

In [17]:
e.dtype.name

'str32'

In [18]:
#datatype can be choosen by giving argumen dtype to the function
f = np.array([[1,2,3],[4,5,1]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 1.+0.j]])

Intrinsic creation of an array

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3, 15, 3)

array([ 3,  6,  9, 12])

The third argument of arrange function can be float data type

In [24]:
np.arange(0, 3, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4])

We can specify the shape of arange function by adding function reshape after the arrange function

In [25]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

linspace(), the first two arguments take the initial and end values but the third argument defines the number of elements between those two values

In [26]:
np.linspace(0, 6, 3)

array([0., 3., 6.])

Creating array of random number using method in random module. We can specify the shape of the array by filling the argument of the method

In [27]:
np.random.random(10)

array([0.1308771 , 0.32368034, 0.98655968, 0.78728334, 0.55407386,
       0.26644281, 0.17335793, 0.58878721, 0.91141609, 0.05575199])

In [28]:
np.random.random((3,4))

array([[0.62046423, 0.33117707, 0.45500958, 0.27745503],
       [0.2201278 , 0.89526123, 0.41253732, 0.15407993],
       [0.9005607 , 0.1491262 , 0.89124596, 0.37493122]])

# Basic Operations

In [29]:
a = np.arange(4)
a

array([0, 1, 2, 3])

We can do addition and multiplication an array with scalar

In [30]:
a+3

array([3, 4, 5, 6])

In [31]:
a*4

array([ 0,  4,  8, 12])

We can also do addition and multiplication between arrays

In [32]:
b = np.arange(4,8)

In [33]:
a+b

array([ 4,  6,  8, 10])

In [34]:
a-b

array([-4, -4, -4, -4])

In [35]:
a*b

array([ 0,  5, 12, 21])

we can also do it when we assign value b to the numpy sin/sqrt function

In [36]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [37]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [38]:
A = np.arange(0,9).reshape(3,3)

In [39]:
B = np.ones((3,3))

In [40]:
A*B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

Doing dot product between two arrays

In [41]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

Alternative doing dot product

In [42]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [43]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

Increment and decrement operators

In [44]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [45]:
a += 1

In [46]:
a

array([1, 2, 3, 4])

In [47]:
a -= 1
a

array([0, 1, 2, 3])

In [48]:
a += 4
a

array([4, 5, 6, 7])

In [49]:
a *= 2

In [52]:
a

array([ 8, 10, 12, 14])

Aggregate Functions

In [54]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])

In [55]:
a.sum()

15.0

In [56]:
a.min()

0.3

In [57]:
a.max()

5.7

In [58]:
a.mean()

3.0

In [59]:
a.std()

2.0079840636817816