Indexing one dimensional array

In [2]:
import numpy as np

In [3]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [4]:
a[4]

14

In [5]:
a[-1]

15

In [6]:
a[[1,4,5]]

array([11, 14, 15])

Indexing two dimensional array (Matrices). The first is the row, and the second one is the column index

In [7]:
A = np.arange(0, 9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
A[0,0]

0

In [9]:
A[1,2]

5

Slicing

In [10]:
a = np.arange(0, 6)
a

array([0, 1, 2, 3, 4, 5])

In [11]:
a[0:2]

array([0, 1])

In [12]:
a[1:5]

array([1, 2, 3, 4])

When we input the third number, it specifies the gap in the sequence between one element and the next one

In [13]:
a[1:6:2]

array([1, 3, 5])

If we omit the first number it will specify it as 0, when we omit the second number it will specify it as the max index of the array, but when we omit the third number it will specify as 1 (no gap between element)

In [15]:
a[:3:1]

array([0, 1, 2])

In [16]:
a[2::1]

array([2, 3, 4, 5])

In [17]:
a[1:3:]

array([1, 2])

In [19]:
A = np.arange(10,19).reshape(3,3)
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [37]:
A[0,:]

array([10, 11, 12])

In [38]:
A[:,0]

array([10, 13, 16])

In [39]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [40]:
A[[0,2], 0:2]

array([[10, 11],
       [16, 17]])