In [1]:
import numpy as np

## Iterating an array

In [3]:
a = np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
for element in a:
    print(element)

0
1
2
3
4
5


In [7]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
for element in A:
    print(element)

[0 1 2]
[3 4 5]
[6 7 8]


In [9]:
for row in A:
    for column in row:
        print(column)

0
1
2
3
4
5
6
7
8


In [10]:
for element in A.flat:
    print(element)

0
1
2
3
4
5
6
7
8


## Condition and Boolean Array

In [14]:
B = np.random.random((3,3))
B

array([[0.49374227, 0.11352111, 0.07174612],
       [0.61106455, 0.6240115 , 0.49060749],
       [0.2682394 , 0.675622  , 0.71650736]])

In [15]:
B > 0.5

array([[False, False, False],
       [ True,  True, False],
       [False,  True,  True]])

In [18]:
B[B>0.5]

array([0.61106455, 0.6240115 , 0.675622  , 0.71650736])

## Shape Manipulation

In [19]:
a = np.random.random(12)
a

array([0.82176921, 0.63132197, 0.75001576, 0.57454067, 0.1742624 ,
       0.53923104, 0.2757498 , 0.50493253, 0.64270554, 0.20181603,
       0.17455922, 0.64125142])

In [21]:
A = a.reshape(3,4)
A

array([[0.82176921, 0.63132197, 0.75001576, 0.57454067],
       [0.1742624 , 0.53923104, 0.2757498 , 0.50493253],
       [0.64270554, 0.20181603, 0.17455922, 0.64125142]])

In [22]:
a.shape = (3,4)
a

array([[0.82176921, 0.63132197, 0.75001576, 0.57454067],
       [0.1742624 , 0.53923104, 0.2757498 , 0.50493253],
       [0.64270554, 0.20181603, 0.17455922, 0.64125142]])

In [24]:
# ravel() to change two dimensional array become one dimensional array
a = a.ravel()
a

array([0.82176921, 0.63132197, 0.75001576, 0.57454067, 0.1742624 ,
       0.53923104, 0.2757498 , 0.50493253, 0.64270554, 0.20181603,
       0.17455922, 0.64125142])

In [25]:
a.shape = (12)
a

array([0.82176921, 0.63132197, 0.75001576, 0.57454067, 0.1742624 ,
       0.53923104, 0.2757498 , 0.50493253, 0.64270554, 0.20181603,
       0.17455922, 0.64125142])

In [26]:
A.transpose()

array([[0.82176921, 0.1742624 , 0.64270554],
       [0.63132197, 0.53923104, 0.20181603],
       [0.75001576, 0.2757498 , 0.17455922],
       [0.57454067, 0.50493253, 0.64125142]])