# Array Manipulation

In [1]:
import numpy as np

### Joining Array

In [2]:
A = np.zeros((3,3))
B = np.ones((3,3))

In [4]:
np.vstack((A,B))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.hstack((A,B))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

In [7]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
np.row_stack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Splitting Arrays

In [10]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
[B,C] = np.hsplit(A,2)

In [12]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [13]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [15]:
[B,C] = np.vsplit(A,2)

In [16]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
[A1, A2, A3] = np.split(A, [1,3], axis=1)

In [24]:
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [25]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [26]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [27]:
# We can change the split for axis = 0 (row)
[A1, A2, A3] = np.split(A, [1,3], axis=0)

In [28]:
A1

array([[0, 1, 2, 3]])

In [29]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
A3

array([[12, 13, 14, 15]])

# General Concepts

### Copies/Views

In [33]:
a = np.array([1,2,3,4])

In [34]:
#This is not a copy of an array, it is just the another way to call a array
b = a

In [35]:
b

array([1, 2, 3, 4])

In [36]:
a[2] = 0
b

array([1, 2, 0, 4])

In [37]:
#This is a view
c = a[0:2]
c

array([1, 2])

In [38]:
a[0] = 0
c

array([0, 2])

In [39]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [40]:
#This is how to copy array
c = a.copy()

In [41]:
a[0] = 0
c

array([1, 2, 3, 4])